<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RazorClassLibrary>true</RazorClassLibrary>
        <EnableDefaultEmbeddedStaticWebAssets>true</EnableDefaultEmbeddedStaticWebAssets>
        <StaticWebAssetBasePath>dx</StaticWebAssetBasePath>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ballware.shared.authorization" Version="0.1.0" />
      <PackageReference Include="DevExpress.AspNetCore.Reporting" Version="25.1.5" />
      <PackageReference Include="DevExpress.Blazor.Reporting.JSBasedControls" Version="25.1.5" />
      <PackageReference Include="DevExpress.Blazor.Reporting.Viewer" Version="25.1.5" />
      <PackageReference Include="DevExpress.Drawing" Version="25.1.5" />
      <PackageReference Include="DevExpress.Drawing.Skia" Version="25.1.5" />
      <PackageReference Include="DevExpress.Pdf.SkiaRenderer" Version="25.1.5" />
      <PackageReference Include="DevExpress.Web.Reporting.Common" Version="25.1.5" />
      <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.20" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
      <PackageReference Include="Quartz" Version="3.8.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ballware.Document.Metadata\Ballware.Document.Metadata.csproj" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="App.razor" />
      <AdditionalFiles Include="Components\_Imports.razor" />
    </ItemGroup>

</Project>
