// <auto-generated />
using System;
using Ballware.Document.Data.Ef.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ballware.Document.Data.Ef.Postgres.Migrations
{
    [DbContext(typeof(DocumentDbContext))]
    [Migration("20250817090313_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ballware.Document.Data.Persistables.Document", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreateStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_stamp");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Entity")
                        .HasColumnType("text")
                        .HasColumnName("entity");

                    b.Property<DateTime?>("LastChangeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_change_stamp");

                    b.Property<Guid?>("LastChangerId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_changer_id");

                    b.Property<string>("ReportParameter")
                        .HasColumnType("text")
                        .HasColumnName("report_parameter");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("pk_document");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_document_tenant_id");

                    b.HasIndex("TenantId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_document_tenant_id_uuid");

                    b.ToTable("document", (string)null);
                });

            modelBuilder.Entity("Ballware.Document.Data.Persistables.Notification", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<DateTime?>("CreateStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_stamp");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentParams")
                        .HasColumnType("text")
                        .HasColumnName("document_params");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("identifier");

                    b.Property<DateTime?>("LastChangeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_change_stamp");

                    b.Property<Guid?>("LastChangerId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_changer_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_notification_tenant_id");

                    b.HasIndex("TenantId", "Identifier")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_tenant_id_identifier");

                    b.HasIndex("TenantId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_notification_tenant_id_uuid");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Ballware.Document.Data.Persistables.Subscription", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long?>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool>("Attachment")
                        .HasColumnType("boolean")
                        .HasColumnName("attachment");

                    b.Property<string>("AttachmentFileName")
                        .HasColumnType("text")
                        .HasColumnName("attachment_file_name");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTime?>("CreateStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_stamp");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<DateTime?>("LastChangeStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_change_stamp");

                    b.Property<Guid?>("LastChangerId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_changer_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastSendStamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_send_stamp");

                    b.Property<string>("Mail")
                        .HasColumnType("text")
                        .HasColumnName("mail");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid")
                        .HasColumnName("uuid");

                    b.HasKey("Id")
                        .HasName("pk_subscription");

                    b.HasIndex("Frequency")
                        .HasDatabaseName("ix_subscription_frequency");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_subscription_tenant_id");

                    b.HasIndex("TenantId", "Uuid")
                        .IsUnique()
                        .HasDatabaseName("ix_subscription_tenant_id_uuid");

                    b.ToTable("subscription", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
